# Generated by Django 5.0.2 on 2024-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='File', max_length=50),
        ),
    ]
