# Generated by Django 5.0.2 on 2024-04-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_file_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
