# Generated by Django 5.0.2 on 2024-04-12 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_student_back_img'),
        ('repository', '0003_remove_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.student'),
        ),
        migrations.AddField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
