# Generated by Django 5.0.2 on 2024-08-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_file_back_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, default='Book', max_length=60),
        ),
    ]
