# Generated by Django 5.0.2 on 2024-08-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
