# Generated by Django 5.0.1 on 2024-08-26 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_discussion_img_discussion_topic'),
        ('repository', '0007_file_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('back_img', models.ImageField(blank=True, default='images/597_1.jpg', upload_to='images/books')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.student')),
            ],
        ),
    ]
