# Generated by Django 5.0.1 on 2024-08-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_file_file_name_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
