# Generated by Django 5.0.1 on 2024-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_remove_file_back_img_remove_file_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='img',
            field=models.ImageField(default='discussions/images/books/file.png', upload_to=''),
        ),
    ]
