# Generated by Django 5.0.1 on 2024-08-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_file_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='img',
        ),
    ]
