# Generated by Django 5.0.1 on 2024-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='back_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/backs'),
        ),
    ]
