# Generated by Django 5.0.1 on 2024-08-29 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='back_img',
            field=models.ImageField(blank=True, default='assets/img/user.png', null=True, upload_to='images/backs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 29, 3, 27, 14, 985377, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.FloatField(blank=True, default=4.3, null=True),
        ),
    ]
