# Generated by Django 5.0.1 on 2024-08-29 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_back_img_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 29, 3, 58, 28, 56755, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
