# Generated by Django 5.0.2 on 2024-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='back_img',
            field=models.ImageField(blank=True, default='images/597_1.jpg', upload_to='images/profiles'),
        ),
    ]
