# Generated by Django 5.0.2 on 2024-08-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_discussion_description_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='discussion',
        ),
    ]
