# Generated by Django 5.0.1 on 2024-08-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_discussion_img_discussion_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='votes',
            new_name='dislikes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
